name: Windows

on:
  push:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: windows-latest
    name: CMake v3.${{ matrix.cmake_version }}
    strategy:
      fail-fast: false
      matrix:
        cmake_version: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
        configurations: ['Debug','Release','']
        generators: ['NMake Makefiles','MSYS Makefiles', 'MinGW Makefiles','Ninja','Ninja Multi-Config','Visual Studio 17 2022']
        exclude:
          - cmake_version: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
            generators: 'Ninja Multi-Config'
          - cmake_version: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]
            generators: 'Ninja Multi-Config'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: ⬇️ Setup CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ~3.${{ matrix.cmake_version }}
          ninjaVersion: ^1

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: ⚙️ run-cmake (configure)
        uses: cmake-tools/run-cmake@v0-alpha
        id: 'configure_ninja'
        with:
          mode: configure
          generator: ${{ matrix.generators }}
          install_prefix: '../install'
          variables:
            CMAKE_BUILD_TYPE:STRING=${{ matrix.cmake_version }}
          
      - name: 🛠️ run-cmake (build)
        uses: cmake-tools/run-cmake@v0-alpha
        id: build
        with:
          mode: build
          clean_first: true
          config: ${{ matrix.cmake_version }}

      - name: 📥 run-cmake (install)
        uses: cmake-tools/run-cmake@v0-alpha
        id: install
        with:
          mode: install
          install_verbose: true

      - name: 🧪 run-ctest
        uses: cmake-tools/run-ctest@v0-alpha
        id: test

      - name: 📦 run-cpack
        uses: cmake-tools/run-cpack@v0-alpha
        id: pack
        with:
          generators: 'STGZ;TBZ2'
